---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- Developer:
    - Github:
        - abbr: GH
          href: https://github.com/

- Directos:
    - Twitch:
        - abbr: TW
          href: https://twitch.tv/

- Videos:
    - YouTube:
        - abbr: YT
          href: https://youtube.com/
